name: Terraform Tasks

on:
  push:
    branches:
      - task_1
  pull_request:
    branches:
      - task_1

env:
  TF_DIR: terraform
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: Deploy Task Infrastructure
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Plan
        run: terraform plan -var="env_suffix=${{ github.ref_name }}"
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve -var="env_suffix=${{ github.ref_name }}"
        working-directory: ${{ env.TF_DIR }}
